# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
remote_theme             : "mmistakes/minimal-mistakes@4.19.1"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-GB"
title                    : "Sahil Arora"
title_separator          : "|"
subtitle                 : ""
name                     : "Sahil Arora"
description              : "Sahil Arora is a problem solver and software engineer based out of India. This is his home on the internet."
url                      : "https://sahilarora535.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "sahilarora535/sahilarora535.github.io"
teaser                   : "/assets/images/teaser.jpg"
logo                     : "/assets/images/icons/Icon-88.png"
words_per_minute         : 200
comments:
  provider               : "disqus"
  disqus:
    shortname            : "sahilarora535"
atom_feed:
  path                   : # blank (default) uses feed.xml
search                   : true
search_full_content      : true
search_provider          : algolia
algolia:
  application_id         : 18HAR1GHEY
  index_name             : personal_website
  search_only_api_key    : bb3d56579ab215b450b2eedaa820ff46
  powered_by             : true

# Social Sharing
twitter:
  username               : sahilarora535
facebook:
  username               : sahilarora535
og_image                 : "/assets/images/icons/Icon-1024.png"
social:
  type                   : Person
  links: # An array of links to social media profiles
    - "https://twitter.com/sahilarora535"
    - "https://www.facebook.com/sahilarora535"
    - "https://instagram.com/sahilarora535"
    - "https://www.linkedin.com/in/sahilarora535"

analytics:
  provider               : false # false (default), "google", "google-universal", "custom"

# Site Author
author:
  name             : "Sahil Arora"
  avatar           : "/assets/images/icons/Icon-1024.png"
  bio              : "Sahil Arora is a problem solver and a software engineer. He loves to eat a lot and struggles constantly with a fat belly."
  location         : "Bengaluru, India"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://sahilarora535.github.io"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/sahilarora535"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sahilarora535"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sahilarora535"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/sahilarora535"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sahilarora535"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/sahilarora535"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sahilarora535"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sahilarora535"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/sahilarora535"
    - label: "Stack Overflow"
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://gitlab.com/sahilarora535"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/sahilarora535"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone:  	Asia/Calcutta


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
