name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  deployments: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install d2
        run: curl -fsSL https://d2lang.com/install.sh | sh -s --
      - name: Install, build, and upload your site
        uses: withastro/action@v4
        with:
          node-version: 22
      - name: Upload dist directory for other deployments
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  unlighthouse_desktop:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Install dependencies
        run: pnpm install -g @unlighthouse/cli puppeteer
      - name: Run Unlighthouse
        run: unlighthouse-ci --config-file unlighthouse-desktop.config.ts --debug --reporter csv --build-static
      - name: List directory
        run: ls -ltra
      - name: Upload unlighthouse static builds
        uses: actions/upload-artifact@v4
        with:
          name: unlighthouse-build-desktop
          path: .unlighthouse/
          retention-days: 7
      - name: Upload ci-report for analysis
        uses: actions/upload-artifact@v4
        with:
          name: ci-report-desktop
          path: .unlighthouse/ci-result.csv
          retention-days: 7

  unlighthouse_mobile:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Install dependencies
        run: pnpm install -g @unlighthouse/cli puppeteer
      - name: Run Unlighthouse
        run: unlighthouse-ci --config-file unlighthouse-mobile.config.ts --debug --reporter csv --build-static
      - name: List directory
        run: ls -ltra
      - name: Upload unlighthouse static builds
        uses: actions/upload-artifact@v4
        with:
          name: unlighthouse-build-mobile
          path: .unlighthouse/
          retention-days: 7
      - name: Upload ci-report for analysis
        uses: actions/upload-artifact@v4
        with:
          name: ci-report-mobile
          path: .unlighthouse/ci-result.csv
          retention-days: 7
